# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичні зайняття №12-13**

### Тема: "Рекурсивні функції"

### **Завдання 1 (1 бал)**

Реалізуйте функцію `cons(head, tail)`, що конструює новий список із довільного елемента `head` й іншого списку `tail`.

Сама по собі функція `cons` не є рекурсивною, однак вона породжує рекурсивну структуру даних, представлену нижче. 

In [15]:
# ВАШ КОД ТУТ
def cons(head, tail=[]):
    result = [head]
    for i in tail:
        result.append(i)
    return result
# ПЕРЕВІРКА

l = cons(3,cons(2,cons(1, [])))

print(f'Result: {l}')

assert l == [3, 2, 1], 'Failed test 1'
assert cons(1) == [1], 'Failed test 2'
print('All tests good!')

Result: [3, 2, 1]
All tests good!


Таким чином, легко уявити, що деякі традиційні структури даних цілком природньо обходяться за допомогою рекурсії.

Напишіть тепер рекурсивну функцію `sum(lst)`, яка сумуватиме список `lst`.

In [42]:
# ВАШ КОД ТУT
def sum(lst, r=0, a=0):
    r += lst[a]
    a += 1
    if len(l) != a:
        return sum(lst, r, a)
    else:
        return r
# ПЕРЕВІРКА

print(sum(l))
assert sum(l) == 6, 'Failed on sum'
print('All tests good!')

6
6
All tests good!


### **Завдання 2 (1 бал)**

Реалізуйте рекурсивну функцію `rrange(begin, end, step)`, що повертає список елементів починаючи з `begin` і закінчуючи `end` невключно, із кроком `step`. Зверніть увагу, що крок може бути від'ємним. Якщо `begin` більше `end` при додатньому кроці (чи менше при від'ємному), або якщо крок нульовий, поверніть порожній список.

Зверніть увагу на тести, приведені нижче.

In [21]:
# ВАШ КОД ТУТ
def rrange(begin, end, step=1, k=None):
    if k is None:
        k = []
    if (begin < end and step > 0) or (begin > end and step < 0):
        k.append(begin)
        begin += step
        rrange(begin, end, step, k)
    elif ((begin > end and step > 0) or/
         (begin < end and step < 0) or step == 0) and len(k) == 0:
        k = []
    return k

# ПЕРЕВІРКА

x = rrange(1, 10)
y = rrange(10, 1, -1)
z = rrange(10, 1, 1)
#print(x, y, z)

assert x == list(range(1, 10)), 'Failed test for simple range'
assert y == list(range(10, 1, -1)), 'Failed test for reverse range'
assert z == list(range(10, 1, 1)), 'Failed test for empty range'
print('All tests good!')

[1, 2, 3, 4, 5, 6, 7, 8, 9]
All tests good!


### **Завдання 3 (2 бали)**

Нехай задано структуру даних, що представляє файли на диску, наступного вигляду:
- файли представлені у вигляді рядків зі своїм іменем;
- папки представлені у вигляді пари `(name, subnodes)`, де `name` — це ім'я папки, а `subnodes` — список з файлів і/або папок, що містяться у ній.

Приклад такої структури наведено нижче у змінній `dirs`.

Реалізуйте рекурсивну функцію `search(dirs, filename)` для пошуку усіх файлів із іменем `filename` у структурі `dirs`. Ця функція має повертати список, що містить повні шляхи до файлу у заданій структурі. Наприклад, `search(dirs, 'file2')` для наведеної нижче структури має повертати список `['/folder1/folder2/file2']`.

_Зауваження 1_: Ви можете, за необхідності, додати до сигнатури функції додаткові параметри, за умови, що вони матимуть значення за замовчуванням. Однак, я стверджую, що таку функцію завжди можна реалізувати використовуючи лише задану кількість параметрів, незалежно від того, чи будете ви використовувати рекурсію з акумулятором чи без.

_Зауваження 2_: Згадайте, що рекурсія буває не тільки безпосередньою, але й опосередкованою, коли послідовність функцій викликає одна одну: `f() -> g() -> ... -> f()`

_Зауваження 3_: Пам'ятайте, що Ви завжди можете використовувати функції `map` та `reduce`. Крім того, ви можете захотіти використати інші функції з модулів `functools` та `itertools`, наприклад `itertools.chain()`. Завдання, однак, можна виконати і без них (хоч це і не дуже зручно).

_Зауваження 4_: На мій смак, версія з акумулятором є більш елегантною, але дещо складнішою в реалізації. Спробуйте реалізувати обидві версії.


*Я , коли очікував , що функція не працюватиме , а вона пройшла усі перевірки з першої спроби

![](https://media.giphy.com/media/VvXg0yjJQgfEQ/giphy.gif)


In [1]:
dirs = [('folder1',['file1',('folder2',['file2','file3']),('folder3',['file3','file4',('folder4', ['file3'])]),'file5'])]

# ВАШ КОД ТУТ
def search(d, name):
    def find(d2, d1, n, w):
        cont = False
        for i in d1:
            for a in d1[i]:
                if type(a) == tuple:
                    cont = True
                    d2[i + " " + a[0]] = a[1]
                if type(a) == str:
                    if a == n:
                        w.append([i, n])
        d1.clear()
        if cont:
            find(d1, d2, n, w)

    def f_res(w, r):
        if len(w) != 0:
            if type(w[0]) == list:
                r.append(str(w[0][0]).split())
                r[-1].append(w[0][1])
                w.pop(0)

                will_append = ""
                for i in range(len(r[0])-1):
                    will_append += "/" + r[0][i] + "/"
                will_append += r[0][-1]
                w.append(will_append)
                r.pop(0)
                f_res(w, r)

    dict1 = dict({})
    dict2 = dict({"": d})
    way = []
    results = []

    find(dict1, dict2, name, way)
    f_res(way, results)
    return way
# ПЕРЕВІРКА

print(search(dirs, 'file1'))
print(search(dirs, 'file2'))
print(search(dirs, 'file3'))
print(search(dirs, 'file4'))
print(search(dirs, 'file5'))
print(search(dirs, 'file6'))
print(search(dirs, 'folder1'))

assert search(dirs, 'file1') == ['/folder1/file1'], 'Failed test for file1'
assert search(dirs, 'file2') == ['/folder1//folder2/file2'], 'Failed test for file2'
assert search(dirs, 'file3') == ['/folder1//folder2/file3', '/folder1//folder3/file3', '/folder1//folder3//folder4/file3'], 'Failed test for file3'
assert search(dirs, 'file4') == ['/folder1//folder3/file4'], 'Failed test for file4'
assert search(dirs, 'file5') == ['/folder1/file5'], 'Failed test for file5'
assert search(dirs, 'file6') == [], 'Failed test for file6'
assert search(dirs, 'folder1') == [], 'Failed test for folder1'
print('All tests good!')

['/folder1/file1']
['/folder1//folder2/file2']
['/folder1//folder2/file3', '/folder1//folder3/file3', '/folder1//folder3//folder4/file3']
['/folder1//folder3/file4']
['/folder1/file5']
[]
[]
All tests good!


### **Завдання 4 (2 бали)**

Реалізуйте [функцію Акермана](https://uk.wikipedia.org/wiki/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D1%96%D1%8F_%D0%90%D0%BA%D0%B5%D1%80%D0%BC%D0%B0%D0%BD%D0%B0), що має такий вигляд:
$$ 
A(m,n) = \begin{cases} 
n + 1, & \quad m = 0; \\
A(m-1, 1), & \quad m>0, n=0; \\
A(m-1, A(m, n-1)), & \quad m > 0, n > 0.
\end{cases}
$$

_Зауваження 1_: Функція Акермана, незважаючи на оманливу простоту свого визначення, має велику обчислювальну складність. На власний страх і ризик, можете спробувати обчислити значення $A(4, 3)$. Не пробуйте робити це у цьому середовищі (і на повільних домашніх компьютерах).

In [50]:
# ВАШ КОД ТУТ
import numpy


def Akk(m,n):
    def func(a, b):
        if a == 0:
            return b+1
        elif b == 0:
            return func(a-1,1)
        else:
            return func(a-1, func(a, b-1))

    matrix = [[0 for i in range(n)] for i in range(m)]
    for i in range(0,m*n):
        matrix[i//n][i%n] = func(i//n,i%n)
    return matrix


matr = numpy.array(Akk(4,5))
print(matr)
# ПЕРЕВІРКА

test_pairs = list((m, n) for m in range(0,4) for n in range(0,5))
results =[[1,  2,  3,  4,   5], 
          [2,  3,  4,  5,   6], 
          [3,  5,  7,  9,  11],
          [5, 13, 29, 61, 125]]
    
for i in range(m*n):
    assert matr[i//n][i%n] == res[i//n][i%n], f'Failed test for (m, n) pair ({m}, {n}): Akk({m}, {n}) = {res}'
print('All tests good!')

[[  1   2   3   4   5]
 [  2   3   4   5   6]
 [  3   5   7   9  11]
 [  5  13  29  61 125]]
All tests good!
